name: Test Incoming Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CM_BIN: /usr/local/bin/checkmake
  CM_URL_LINUX: https://github.com/mrtazz/checkmake/releases/download/0.2.2/checkmake-0.2.2.linux.amd64 # yamllint disable-line

jobs:
  lint:
    name: Run Linters and Vet
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5  # Updated to use version tag instead of commit hash
        with:
          go-version: 1.23.1

      - name: Disable default go problem matcher
        run: echo "::remove-matcher owner=go::"

      - name: Check out code
        uses: actions/checkout@v4  # Updated to use version tag instead of commit hash
        with:
          ref: ${{ github.sha }}

      - name: Extract dependent Pull Requests
        uses: depends-on/depends-on-action@main  # Using the latest stable release tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install checkmake
        run: |
          curl --location --output $CM_BIN --silent $CM_URL_LINUX
          chmod +x $CM_BIN

      - name: Install shfmt (if shell scripts are used)
        run: |
          curl -sSfL https://github.com/mvdan/sh/releases/download/v3.5.0/shfmt_v3.5.0_linux_amd64 -o /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0  # Version tag used consistently
        with:
          version: v1.60
          args: --timeout 10m0s

      - name: Checkmake
        run: checkmake --config=.checkmake Makefile

      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0  # Version tag used
        with:
          files: .

      - name: Run tests
        run: make test  # Corrected from 'Eun test' to 'Run test'
